/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.xdob.pf4boot;

import org.gradle.api.artifacts.Configuration;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'pf4boot-plugin' plugin.
 */
public class Pf4BootPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("java-library");
        project.getPlugins().apply("net.xdob.pf4boot-plugin");

        // Verify the result
        assertNotNull(project.getTasks().findByName("pf4boot"));
        assertNotNull(project.getExtensions().findByName("pf4bootPlugin"));
    }

    @Test public void pluginRegistersConfiguration() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("java-library");
        project.getPlugins().apply("net.xdob.pf4boot-plugin");

        // Verify the result
        Configuration api = project.getConfigurations().findByName("api");
        assertNotNull(api);
        Configuration bundle = project.getConfigurations().findByName("bundle");
        assertNotNull(bundle);

        Configuration embed = project.getConfigurations().findByName("embed");
        assertNotNull(embed);
        assertTrue(api.getExtendsFrom().contains(embed));

        Configuration plugin = project.getConfigurations().findByName("plugin");
        assertNotNull(plugin);


    }
}
