/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.xdob.pf4boot;

import org.gradle.api.artifacts.Configuration;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'pf4boot-plugin' plugin.
 */
public class Pf4BootPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("pf4boot-plugin");

        // Verify the result
        assertNotNull(project.getTasks().findByName("buildPf4bootPlugin"));
    }

    @Test public void pluginRegistersConfiguration() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("pf4boot-plugin");

        // Verify the result
        Configuration inline = project.getConfigurations().findByName("inline");
        assertNotNull(inline);
        Configuration compile = project.getConfigurations().findByName("compile");
        assertNotNull(compile);
        assertTrue(compile.getExtendsFrom().contains(inline));
        Configuration plugin = project.getConfigurations().findByName("plugin");
        assertNotNull(plugin);
        assertFalse(plugin.isTransitive());

    }
}
