/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.xdob.pf4boot;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Properties;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * A simple functional test for the 'net.xdob.pf4boot-plugin' plugin.
 */
public class Pf4bootPluginFunctionalTest {
	@Test
	public void canRunTask4Properties() throws IOException {
		File projectDir = new File("build/functionalTest/canRunTask4Properties");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n");

		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = test-plugin1\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 1.0.0\n" +
						"plugin.provider = unit");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("test-plugin1"));
	}

	@Test
	public void canRunTask4Ext() throws IOException {
		File projectDir = new File("build/functionalTest/canRunTask4Ext");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"pf4bootPlugin {\n" +
						"  id = 'test-plugin2'\n" +
						"  pluginClass = 'net.xdob.TestPlugin'\n" +
						"  version = '1.0.0'\n" +
						"}\n");
		Files.deleteIfExists(new File(projectDir, "plugin.properties").toPath());

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("test-plugin2"));
	}

	@Test
	public void shouldFailWhenPluginIdMissing() throws IOException {
		File projectDir = new File("build/functionalTest/shouldFailWhenPluginIdMissing");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n");
		writeString(new File(projectDir, "plugin.properties"),
				"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 1.0.0\n");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("Invalid pf4boot plugin property 'plugin.id'"));
	}

	@Test
	public void shouldFailWhenPluginClassMissing() throws IOException {
		File projectDir = new File("build/functionalTest/shouldFailWhenPluginClassMissing");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n");
		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = test-plugin3\n" +
						"plugin.version = 1.0.0\n");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("Invalid pf4boot plugin property 'plugin.class'"));
	}

	@Test
	public void shouldFailWhenPluginVersionUnspecified() throws IOException {
		File projectDir = new File("build/functionalTest/shouldFailWhenPluginVersionUnspecified");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n");
		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = test-plugin4\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = unspecified\n");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("Avoid using 'unspecified'."));
	}

	@Test
	public void shouldPackageGeneratedPropertiesAndDependencies() throws IOException {
		File projectDir = new File("build/functionalTest/shouldPackageGeneratedPropertiesAndDependencies");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-package-artifact'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '1.2.3'\n" +
						"dependencies {\n" +
						"  bundle files('package-bundle.jar')\n" +
						"  bundleOnly files('package-bundleOnly.jar')\n" +
						"  embed files('package-embed.jar')\n" +
						"}\n");

		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = packaged-test-plugin\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 1.2.3\n" +
						"plugin.provider = packaged-provider\n");
		writeString(new File(projectDir, "package-bundle.jar"), "bundle jar");
		writeString(new File(projectDir, "package-bundleOnly.jar"), "bundleOnly jar");
		writeString(new File(projectDir, "package-embed.jar"), "embed jar");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		File zipFile = new File(projectDir, "build/libs/pf4boot-package-artifact-1.2.3.zip");
		assertTrue(zipFile.getAbsolutePath(), zipFile.exists());

		List<String> zipEntries = listZipEntries(zipFile);
		assertTrue(zipEntries.contains("plugin.properties") || zipEntries.contains("generated/pf4boot/plugin.properties"));
		assertTrue(zipEntries.contains("lib/pf4boot-package-artifact-1.2.3.jar"));
		assertTrue(zipEntries.contains("lib/package-bundle.jar"));
		assertTrue(zipEntries.contains("lib/package-bundleOnly.jar"));
		assertTrue(zipEntries.contains("lib/package-embed.jar"));

		Properties generatedProperties = readPluginPropertiesFromZip(zipFile);
		assertEquals("packaged-test-plugin", generatedProperties.getProperty("plugin.id"));
		assertEquals("net.xdob.TestPlugin", generatedProperties.getProperty("plugin.class"));
		assertEquals("1.2.3", generatedProperties.getProperty("plugin.version"));
		assertEquals("packaged-provider", generatedProperties.getProperty("plugin.provider"));
	}

	@Test
	public void shouldPreferExtensionPropertiesOverPluginPropertiesFile() throws IOException {
		File projectDir = new File("build/functionalTest/shouldPreferExtensionPropertiesOverPluginPropertiesFile");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-property-priority'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n"						+
						"}\n" +
						"version = '2.0.0'\n" +
						"pf4bootPlugin {\n" +
						"  provider = 'extension-provider'\n" +
						"}\n");

		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = priority-plugin\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 2.0.0\n" +
						"plugin.provider = properties-provider\n");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		File zipFile = new File(projectDir, "build/libs/pf4boot-property-priority-2.0.0.zip");
		Properties generatedProperties = readPluginPropertiesFromZip(zipFile);

		assertEquals("priority-plugin", generatedProperties.getProperty("plugin.id"));
		assertEquals("net.xdob.TestPlugin", generatedProperties.getProperty("plugin.class"));
		assertEquals("extension-provider", generatedProperties.getProperty("plugin.provider"));
	}

	@Test
	public void shouldKeepUtf8ContentInGeneratedProperties() throws IOException {
		File projectDir = new File("build/functionalTest/shouldKeepUtf8ContentInGeneratedProperties");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-utf8'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '3.0.0'\n");

		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = utf8-plugin\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 3.0.0\n" +
						"plugin.description = 这是一个中文描述\n" +
						"plugin.requires = 依赖中文依赖\n");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		File zipFile = new File(projectDir, "build/libs/pf4boot-utf8-3.0.0.zip");
		Properties generatedProperties = readPluginPropertiesFromZip(zipFile);

		assertEquals("这是一个中文描述", generatedProperties.getProperty("plugin.description"));
		assertEquals("依赖中文依赖", generatedProperties.getProperty("plugin.requires"));
	}

	@Test
	public void shouldRebuildAfterPluginPropertiesChange() throws IOException {
		File projectDir = new File("build/functionalTest/shouldRebuildAfterPluginPropertiesChange");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-rebuild'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '4.0.0'\n");

		File pluginProperties = new File(projectDir, "plugin.properties");
		writeString(pluginProperties,
				"plugin.id = rebuild-plugin-before\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 4.0.0\n");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		File zipFile = new File(projectDir, "build/libs/pf4boot-rebuild-4.0.0.zip");
		Properties generatedPropertiesBefore = readPluginPropertiesFromZip(zipFile);
		assertEquals("rebuild-plugin-before", generatedPropertiesBefore.getProperty("plugin.id"));

		writeString(pluginProperties,
				"plugin.id = rebuild-plugin-after\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = 4.0.0\n");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		Properties generatedPropertiesAfter = readPluginPropertiesFromZip(zipFile);
		assertEquals("rebuild-plugin-after", generatedPropertiesAfter.getProperty("plugin.id"));
		assertNotEquals(
				generatedPropertiesBefore.getProperty("plugin.id"),
				generatedPropertiesAfter.getProperty("plugin.id")
		);
	}

	@Test
	public void shouldExposePlatformApiInPluginLocalRuntimeClasspath() throws IOException {
		File projectDir = new File("build/functionalTest/shouldExposePlatformApiInPluginLocalRuntimeClasspath");
		Files.createDirectories(projectDir.toPath());
		createMavenJar(projectDir, "org.slf4j", "slf4j-api", "2.0.7", "");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-platform-local-runtime'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"repositories { maven { url = uri('repo') } }\n" +
						"dependencies { platformApi 'org.slf4j:slf4j-api:2.0.7' }\n" +
						"tasks.register('printLocalRuntime') {\n" +
						"  doLast { println configurations.pluginLocalRuntimeClasspath.files.collect { it.name }.sort().join(',') }\n" +
						"}\n");
		writePluginProperties(projectDir, "platform-local-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("printLocalRuntime")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("slf4j-api-2.0.7.jar"));
	}

	@Test
	public void shouldMakePlatformApiCompileVisibleLocalRuntimeVisibleAndNotPackaged() throws IOException {
		File projectDir = new File("build/functionalTest/shouldMakePlatformApiCompileVisibleLocalRuntimeVisibleAndNotPackaged");
		File platformSourceDir = new File(projectDir, "slf4j-api/src/main/java/org/slf4j");
		File pluginSourceDir = new File(projectDir, "plugin-demo/src/main/java/demo");
		Files.createDirectories(platformSourceDir.toPath());
		Files.createDirectories(pluginSourceDir.toPath());

		writeString(new File(projectDir, "settings.gradle"),
				"rootProject.name = 'pf4boot-platform-api-contract'\n" +
						"include 'slf4j-api', 'plugin-demo'\n");
		writeString(new File(projectDir, "build.gradle"), "");
		writeString(new File(projectDir, "slf4j-api/build.gradle"),
				"plugins { id 'java-library' }\n" +
						"group = 'org.slf4j'\n" +
						"version = '2.0.7'\n");
		writeString(new File(platformSourceDir, "Logger.java"),
				"package org.slf4j;\n" +
						"public interface Logger {\n" +
						"  void info(String message);\n" +
						"}\n");
		writeString(new File(platformSourceDir, "LoggerFactory.java"),
				"package org.slf4j;\n" +
						"public final class LoggerFactory {\n" +
						"  private LoggerFactory() {}\n" +
						"  public static Logger getLogger(Class<?> type) { return new NoopLogger(); }\n" +
						"  private static final class NoopLogger implements Logger {\n" +
						"    public void info(String message) {}\n" +
						"  }\n" +
						"}\n");
		writeString(new File(projectDir, "plugin-demo/build.gradle"),
				"plugins {\n" +
						"  id 'java'\n" +
						"  id 'net.xdob.pf4boot-plugin'\n" +
						"}\n" +
						"version = '1.0.0'\n" +
						"dependencies { platformApi project(':slf4j-api') }\n" +
						"tasks.register('printLocalRuntime') {\n" +
						"  dependsOn ':slf4j-api:jar'\n" +
						"  doLast { println configurations.pluginLocalRuntimeClasspath.files.collect { it.name }.sort().join(',') }\n" +
						"}\n");
		writeString(new File(pluginSourceDir, "PluginMain.java"),
				"package demo;\n" +
						"import org.slf4j.Logger;\n" +
						"import org.slf4j.LoggerFactory;\n" +
						"public final class PluginMain {\n" +
						"  private static final Logger LOG = LoggerFactory.getLogger(PluginMain.class);\n" +
						"  public static void main(String[] args) { LOG.info(\"local\"); }\n" +
						"}\n");
		writePluginProperties(new File(projectDir, "plugin-demo"), "platform-api-contract-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments(":plugin-demo:compileJava", ":plugin-demo:printLocalRuntime", ":plugin-demo:pf4boot")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("slf4j-api-2.0.7.jar"));
		File zipFile = new File(projectDir, "plugin-demo/build/libs/plugin-demo-1.0.0.zip");
		List<String> zipEntries = listZipEntries(zipFile);
		assertTrue(zipEntries.contains("lib/plugin-demo-1.0.0.jar"));
		for (String entry : zipEntries) {
			assertTrue(entry, !entry.contains("slf4j-api"));
		}
	}

	@Test
	public void shouldKeepBundledLibraryPlatformApiVisibleForLibraryAndPluginLocalRuntimeButNotPackaged() throws IOException {
		File projectDir = new File("build/functionalTest/shouldKeepBundledLibraryPlatformApiVisibleForLibraryAndPluginLocalRuntimeButNotPackaged");
		File platformSourceDir = new File(projectDir, "slf4j-api/src/main/java/org/slf4j");
		File librarySourceDir = new File(projectDir, "apacheds-lib/src/main/java/demo/lib");
		File libraryTestSourceDir = new File(projectDir, "apacheds-lib/src/test/java/demo/lib");
		Files.createDirectories(platformSourceDir.toPath());
		Files.createDirectories(librarySourceDir.toPath());
		Files.createDirectories(libraryTestSourceDir.toPath());
		Files.createDirectories(new File(projectDir, "plugin-demo").toPath());

		writeString(new File(projectDir, "settings.gradle"),
				"rootProject.name = 'pf4boot-library-platform-api-contract'\n" +
						"include 'slf4j-api', 'apacheds-lib', 'plugin-demo'\n");
		writeString(new File(projectDir, "build.gradle"), "");
		writeString(new File(projectDir, "slf4j-api/build.gradle"),
				"plugins { id 'java-library' }\n" +
						"group = 'org.slf4j'\n" +
						"version = '2.0.7'\n");
		writeString(new File(platformSourceDir, "Logger.java"),
				"package org.slf4j;\n" +
						"public interface Logger {\n" +
						"  void info(String message);\n" +
						"}\n");
		writeString(new File(platformSourceDir, "LoggerFactory.java"),
				"package org.slf4j;\n" +
						"public final class LoggerFactory {\n" +
						"  private LoggerFactory() {}\n" +
						"  public static Logger getLogger(Class<?> type) { return new NoopLogger(); }\n" +
						"  private static final class NoopLogger implements Logger {\n" +
						"    public void info(String message) {}\n" +
						"  }\n" +
						"}\n");
		writeString(new File(projectDir, "apacheds-lib/build.gradle"),
				"plugins {\n" +
						"  id 'java-library'\n" +
						"  id 'net.xdob.pf4boot'\n" +
						"}\n" +
						"group = 'demo'\n" +
						"version = '1.0.0'\n" +
						"dependencies { platformApi project(':slf4j-api') }\n" +
						"tasks.register('printRuntimeClasspaths') {\n" +
						"  dependsOn ':slf4j-api:jar'\n" +
						"  doLast {\n" +
						"    println 'LIB_RUNTIME=' + configurations.runtimeClasspath.files.collect { it.name }.sort().join(',')\n" +
						"    println 'LIB_TEST_RUNTIME=' + configurations.testRuntimeClasspath.files.collect { it.name }.sort().join(',')\n" +
						"  }\n" +
						"}\n");
		writeString(new File(librarySourceDir, "LibraryMain.java"),
				"package demo.lib;\n" +
						"import org.slf4j.Logger;\n" +
						"import org.slf4j.LoggerFactory;\n" +
						"public final class LibraryMain {\n" +
						"  private static final Logger LOG = LoggerFactory.getLogger(LibraryMain.class);\n" +
						"  public static void use() { LOG.info(\"library\"); }\n" +
						"}\n");
		writeString(new File(libraryTestSourceDir, "LibraryMainTest.java"),
				"package demo.lib;\n" +
						"import org.slf4j.Logger;\n" +
						"import org.slf4j.LoggerFactory;\n" +
						"public final class LibraryMainTest {\n" +
						"  private static final Logger LOG = LoggerFactory.getLogger(LibraryMainTest.class);\n" +
						"  public void compileOnly() { LOG.info(\"test\"); }\n" +
						"}\n");
		writeString(new File(projectDir, "plugin-demo/build.gradle"),
				"plugins {\n" +
						"  id 'java'\n" +
						"  id 'net.xdob.pf4boot-plugin'\n" +
						"}\n" +
						"version = '1.0.0'\n" +
						"dependencies { bundle project(':apacheds-lib') }\n" +
						"tasks.register('printPluginLocalRuntime') {\n" +
						"  dependsOn ':slf4j-api:jar'\n" +
						"  doLast { println 'PLUGIN_LOCAL_RUNTIME=' + configurations.pluginLocalRuntimeClasspath.files.collect { it.name }.sort().join(',') }\n" +
						"}\n");
		writePluginProperties(new File(projectDir, "plugin-demo"), "library-platform-api-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments(
						":apacheds-lib:compileJava",
						":apacheds-lib:compileTestJava",
						":apacheds-lib:printRuntimeClasspaths",
						":plugin-demo:printPluginLocalRuntime",
						":plugin-demo:pf4boot"
				)
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("LIB_RUNTIME=slf4j-api-2.0.7.jar"));
		assertTrue(result.getOutput(), result.getOutput().contains("LIB_TEST_RUNTIME=slf4j-api-2.0.7.jar"));
		assertTrue(result.getOutput(), result.getOutput().contains("PLUGIN_LOCAL_RUNTIME=slf4j-api-2.0.7.jar"));
		File zipFile = new File(projectDir, "plugin-demo/build/libs/plugin-demo-1.0.0.zip");
		List<String> zipEntries = listZipEntries(zipFile);
		assertTrue(zipEntries.contains("lib/apacheds-lib-1.0.0.jar"));
		for (String entry : zipEntries) {
			assertTrue(entry, !entry.contains("slf4j-api"));
		}
	}

	@Test
	public void shouldNotPackagePlatformApiByDefault() throws IOException {
		File projectDir = new File("build/functionalTest/shouldNotPackagePlatformApiByDefault");
		Files.createDirectories(projectDir.toPath());
		createMavenJar(projectDir, "org.slf4j", "slf4j-api", "2.0.7", "");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-platform-not-packaged'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '1.0.0'\n" +
						"repositories { maven { url = uri('repo') } }\n" +
						"dependencies { platformApi 'org.slf4j:slf4j-api:2.0.7' }\n");
		writePluginProperties(projectDir, "platform-not-packaged-plugin", "1.0.0");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4boot")
				.withProjectDir(projectDir)
				.build();

		File zipFile = new File(projectDir, "build/libs/pf4boot-platform-not-packaged-1.0.0.zip");
		List<String> zipEntries = listZipEntries(zipFile);
		assertTrue(zipEntries.contains("lib/pf4boot-platform-not-packaged-1.0.0.jar"));
		for (String entry : zipEntries) {
			assertTrue(entry, !entry.contains("slf4j-api"));
		}
	}

	@Test
	public void shouldKeepBundleOnlyNonTransitiveWhenReportingPackagedDependencies() throws IOException {
		File projectDir = new File("build/functionalTest/shouldKeepBundleOnlyNonTransitiveWhenReportingPackagedDependencies");
		Files.createDirectories(projectDir.toPath());
		createMavenJar(projectDir, "demo", "transitive-lib", "1.0.0", "");
		createMavenJar(projectDir, "demo", "direct-lib", "1.0.0",
				"<dependencies><dependency><groupId>demo</groupId><artifactId>transitive-lib</artifactId><version>1.0.0</version></dependency></dependencies>");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-bundle-only-report'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"repositories { maven { url = uri('repo') } }\n" +
						"dependencies { bundleOnly 'demo:direct-lib:1.0.0' }\n");
		writePluginProperties(projectDir, "bundle-only-report-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4bootDependencies")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("demo:direct-lib:1.0.0"));
		assertTrue(result.getOutput(), !result.getOutput().contains("demo:transitive-lib:1.0.0"));
	}

	@Test
	public void shouldReportPackagedPlatformAndLocalRuntimeDependencies() throws IOException {
		File projectDir = new File("build/functionalTest/shouldReportPackagedPlatformAndLocalRuntimeDependencies");
		Files.createDirectories(projectDir.toPath());
		createMavenJar(projectDir, "org.slf4j", "slf4j-api", "2.0.7", "");
		createMavenJar(projectDir, "demo", "bundle-lib", "1.0.0", "");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-dependency-report'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"repositories { maven { url = uri('repo') } }\n" +
						"dependencies {\n" +
						"  platformApi 'org.slf4j:slf4j-api:2.0.7'\n" +
						"  bundle 'demo:bundle-lib:1.0.0'\n" +
						"}\n");
		writePluginProperties(projectDir, "dependency-report-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("pf4bootDependencies")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("Packaged bundle dependencies"));
		assertTrue(result.getOutput(), result.getOutput().contains("Platform dependencies"));
		assertTrue(result.getOutput(), result.getOutput().contains("Local runtime dependencies"));
		assertTrue(result.getOutput(), result.getOutput().contains("demo:bundle-lib:1.0.0"));
		assertTrue(result.getOutput(), result.getOutput().contains("org.slf4j:slf4j-api:2.0.7"));
	}

	@Test
	public void shouldWarnWhenPackagedDependencyDuplicatesPlatformDependency() throws IOException {
		File projectDir = new File("build/functionalTest/shouldWarnWhenPackagedDependencyDuplicatesPlatformDependency");
		Files.createDirectories(projectDir.toPath());
		createMavenJar(projectDir, "org.slf4j", "slf4j-api", "2.0.7", "");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-duplicate-report'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"repositories { maven { url = uri('repo') } }\n" +
						"dependencies {\n" +
						"  platformApi 'org.slf4j:slf4j-api:2.0.7'\n" +
						"  bundle 'org.slf4j:slf4j-api:2.0.7'\n" +
						"}\n");
		writePluginProperties(projectDir, "duplicate-report-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("checkPluginRuntimeClasspath")
				.withProjectDir(projectDir)
				.build();

		assertTrue(result.getOutput(), result.getOutput().contains("Duplicate pf4boot dependency"));
	}

	@Test
	public void shouldReportClassReferenceForKnownMissingPlatformApi() throws IOException {
		File projectDir = new File("build/functionalTest/shouldReportClassReferenceForKnownMissingPlatformApi");
		Files.createDirectories(projectDir.toPath());
		createJarWithClassReference(new File(projectDir, "needs-slf4j.jar"), "org/slf4j/LoggerFactory");

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-bytecode-diagnostic'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"dependencies { bundle files('needs-slf4j.jar') }\n");
		writePluginProperties(projectDir, "bytecode-diagnostic-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("checkPluginRuntimeClasspath")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("org.slf4j:slf4j-api"));
		assertTrue(result.getOutput(), result.getOutput().contains("needs-slf4j.jar"));
	}

	@Test
	public void shouldVerifyReleaseReadinessForCurrentVersion() throws IOException {
		File projectDir = new File("build/functionalTest/shouldVerifyReleaseReadinessForCurrentVersion");
		Files.createDirectories(new File(projectDir, "docs").toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-release-ready'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '1.0.0'\n");
		writePluginProperties(projectDir, "release-ready-plugin", "1.0.0");
		writeReleaseDocs(projectDir, "1.0.0");

		GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("verifyReleaseReadiness")
				.withProjectDir(projectDir)
				.build();
	}

	@Test
	public void shouldFailReleaseReadinessWhenVersionIsSnapshot() throws IOException {
		File projectDir = new File("build/functionalTest/shouldFailReleaseReadinessWhenVersionIsSnapshot");
		Files.createDirectories(new File(projectDir, "docs").toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-release-snapshot'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '1.0.0-SNAPSHOT'\n");
		writePluginProperties(projectDir, "release-snapshot-plugin", "1.0.0-SNAPSHOT");
		writeReleaseDocs(projectDir, "1.0.0-SNAPSHOT");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("verifyReleaseReadiness")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("must not be SNAPSHOT"));
	}

	@Test
	public void shouldFailReleaseTagWhenTagDoesNotPointToHead() throws IOException {
		File projectDir = new File("build/functionalTest/shouldFailReleaseTagWhenTagDoesNotPointToHead");
		Files.createDirectories(projectDir.toPath());

		writeString(new File(projectDir, "settings.gradle"), "rootProject.name = 'pf4boot-release-tag'");
		writeString(new File(projectDir, "build.gradle"),
				"plugins {\n" +
						"  id('java')\n" +
						"  id('net.xdob.pf4boot-plugin')\n" +
						"}\n" +
						"version = '1.0.0'\n");
		writePluginProperties(projectDir, "release-tag-plugin", "1.0.0");

		BuildResult result = GradleRunner.create()
				.forwardOutput()
				.withPluginClasspath()
				.withArguments("verifyReleaseTag")
				.withProjectDir(projectDir)
				.buildAndFail();

		assertTrue(result.getOutput(), result.getOutput().contains("Release tag v1.0.0 does not point to HEAD"));
	}


  private void writeString(File file, String string) throws IOException {
    try (Writer writer = Files.newBufferedWriter(file.toPath(), StandardCharsets.UTF_8)) {
      writer.write(string);
    }
  }

	private void writePluginProperties(File projectDir, String pluginId, String version) throws IOException {
		writeString(new File(projectDir, "plugin.properties"),
				"plugin.id = " + pluginId + "\n" +
						"plugin.class = net.xdob.TestPlugin\n" +
						"plugin.version = " + version + "\n");
	}

	private void writeReleaseDocs(File projectDir, String version) throws IOException {
		writeString(new File(projectDir, "CHANGELOG.md"), "## [" + version + "]\n");
		writeString(new File(projectDir, "CHANGELOG_EN.md"), "## [" + version + "]\n");
		writeString(new File(projectDir, "README.md"), "classpath \"net.xdob.pf4boot:pf4boot-plugin:" + version + "\"\n");
		writeString(new File(projectDir, "README_EN.md"), "classpath \"net.xdob.pf4boot:pf4boot-plugin:" + version + "\"\n");
		writeString(new File(projectDir, "docs/usage-zh.md"), "classpath \"net.xdob.pf4boot:pf4boot-plugin:" + version + "\"\n");
		writeString(new File(projectDir, "docs/usage-en.md"), "classpath \"net.xdob.pf4boot:pf4boot-plugin:" + version + "\"\n");
	}

	private void createMavenJar(File projectDir, String group, String artifact, String version, String pomBody) throws IOException {
		File artifactDir = new File(projectDir, "repo/" + group.replace('.', '/') + "/" + artifact + "/" + version);
		Files.createDirectories(artifactDir.toPath());
		writeString(new File(artifactDir, artifact + "-" + version + ".pom"),
				"<project><modelVersion>4.0.0</modelVersion>" +
						"<groupId>" + group + "</groupId>" +
						"<artifactId>" + artifact + "</artifactId>" +
						"<version>" + version + "</version>" +
						pomBody +
						"</project>");
		createJarWithClassReference(new File(artifactDir, artifact + "-" + version + ".jar"), artifact.replace('-', '/') + "/Marker");
	}

	private void createJarWithClassReference(File jarFile, String reference) throws IOException {
		try (JarOutputStream jar = new JarOutputStream(Files.newOutputStream(jarFile.toPath()))) {
			JarEntry entry = new JarEntry("demo/Marker.class");
			jar.putNextEntry(entry);
			jar.write(("not-a-real-class " + reference).getBytes(StandardCharsets.UTF_8));
			jar.closeEntry();
		}
	}

	private List<String> listZipEntries(File zipFile) throws IOException {
		List<String> entryNames = new ArrayList<>();
		try (ZipFile zip = new ZipFile(zipFile)) {
			Enumeration<? extends ZipEntry> entries = zip.entries();
			while (entries.hasMoreElements()) {
				entryNames.add(entries.nextElement().getName());
			}
		}
		return entryNames;
	}

	private Properties readPluginPropertiesFromZip(File zipFile) throws IOException {
		try (ZipFile zip = new ZipFile(zipFile)) {
			ZipEntry pluginPropertiesEntry = zip.getEntry("generated/pf4boot/plugin.properties");
			if (pluginPropertiesEntry == null) {
				pluginPropertiesEntry = zip.getEntry("plugin.properties");
			}
			assertNotNull(pluginPropertiesEntry);

			try (InputStream input = zip.getInputStream(pluginPropertiesEntry)) {
				Properties properties = new Properties();
				properties.load(new InputStreamReader(input, StandardCharsets.UTF_8));
				return properties;
			}
		}
	}
}
